"""Initial migration.

Revision ID: 1d39f5f095a5
Revises: 
Create Date: 2024-08-23 15:25:27.424187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d39f5f095a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('revista', sa.String(length=255), nullable=False),
    sa.Column('issn', sa.String(length=9), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('subarea_id', sa.Integer(), nullable=False),
    sa.Column('autores', sa.String(length=255), nullable=False),
    sa.Column('internacionalizacao', sa.Boolean(), nullable=True),
    sa.Column('classificacao', sa.String(length=10), nullable=True),
    sa.Column('fator_impacto', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_canonico', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_canonico')
    )
    op.create_table('variacao_autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('nome_variacao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variacao_autor')
    op.drop_table('autor')
    op.drop_table('artigo')
    # ### end Alembic commands ###
