"""Create user table

Revision ID: 668e097cf587
Revises: 1d39f5f095a5
Create Date: 2024-09-08 01:53:54.876004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668e097cf587'
down_revision = '1d39f5f095a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('variacao_autor')
    op.drop_table('autor')
    op.drop_table('qualis_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualis_area',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('classificacao', sa.VARCHAR(length=10), nullable=False),
    sa.Column('issn', sa.VARCHAR(length=9), nullable=False),
    sa.Column('subarea_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subarea_id'], ['subarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_canonico', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_canonico')
    )
    op.create_table('variacao_autor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('autor_id', sa.INTEGER(), nullable=False),
    sa.Column('nome_variacao', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
